Pandas

Load the dataset.

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('students.csv')
df.head()

   student_id  name  age       city course  score  attendance
0           1   Ali   21     Lahore     ML     88          95
1           2  Sara   22    Karachi     ML     92          88
2           3  Zara   20     Lahore   Data     79          76
3           4  Omar   23  Islamabad    Web     85          91
4           5  Hina   21    Karachi     ML     95          99


Display the first and last five rows.

In [ ]:

print("First 5 rows:")
print(df.head())
print("\nLast 5 rows:")
print(df.tail())

pd.concat([df.head(), df.tail()])

First 5 rows:
   student_id  name  age       city course  score  attendance
0           1   Ali   21     Lahore     ML     88          95
1           2  Sara   22    Karachi     ML     92          88
2           3  Zara   20     Lahore   Data     79          76
3           4  Omar   23  Islamabad    Web     85          91
4           5  Hina   21    Karachi     ML     95          99

Last 5 rows:
    student_id    name  age       city course  score  attendance
10          11    Noor   22    Karachi     ML     77          80
11          12    Saad   25     Lahore   Data     69          70
12          13    Iqra   20  Islamabad     ML     99          98
13          14  Danish   23    Karachi    Web     45          40
14          15  Mariam   21     Lahore   Data     81          85

    student_id    name  age       city course  score  attendance
0            1     Ali   21     Lahore     ML     88          95
1            2    Sara   22    Karachi     ML     92          88
2            3    Zara   20     Lahore   Data     79          76
3            4    Omar   23  Islamabad    Web     85          91
4            5    Hina   21    Karachi     ML     95          99
10          11    Noor   22    Karachi     ML     77          80
11          12    Saad   25     Lahore   Data     69          70
12          13    Iqra   20  Islamabad     ML     99          98
13          14  Danish   23    Karachi    Web     45          40
14          15  Mariam   21     Lahore   Data     81          85


Display dataset information.

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  15 non-null     int64
 1   name        15 non-null     object
 2   age         15 non-null     int64
 3   city        15 non-null     object
 4   course      15 non-null     object
 5   score       15 non-null     int64
 6   attendance  15 non-null     int64
dtypes: int64(4), object(3)
memory usage: 972.0+ bytes

Find missing values.

In [9]:
df.isnull()        
df.isna()          

df.isnull().sum()

student_id    0
name          0
age           0
city          0
course        0
score         0
attendance    0
dtype: int64


Filter data based on a condition.

In [16]:
df[(df['score']>70)&(df['attendance']>80) & (df['course']=="ML")]

    student_id   name  age       city course  score  attendance
0            1    Ali   21     Lahore     ML     88          95
1            2   Sara   22    Karachi     ML     92          88
4            5   Hina   21    Karachi     ML     95          99
7            8  Usman   20    Karachi     ML     90          94
12          13   Iqra   20  Islamabad     ML     99          98

Calculate summary statistics.

In [19]:
df.describe()

       student_id        age      score  attendance
count   15.000000  15.000000  15.000000   15.000000
mean     8.000000  21.866667  78.400000   79.466667
std      4.472136   1.505545  14.994285   17.315834
min      1.000000  20.000000  45.000000   40.000000
25%      4.500000  21.000000  71.000000   71.000000
50%      8.000000  22.000000  81.000000   85.000000
75%     11.500000  23.000000  89.000000   92.500000
max     15.000000  25.000000  99.000000   99.000000

In [ ]:

print("mean score  :", df['score'].mean())
print("median score:", df['score'].median())
print("std dev     :", df['score'].std())
print("min / max   :", df['score'].min(), "/", df['score'].max())
print("total       :", df['score'].sum())
print("count       :", df['score'].count())

mean score  : 78.4
median score: 81.0
std dev     : 14.994284625435501
min / max   : 45 / 99
total       : 1176
count       : 15

In [18]:
print(df.groupby('course')['score'].mean())

course
Data    69.600000
ML      90.166667
Web     71.750000
Name: score, dtype: float64