# Pandas Basics

A hands-on walkthrough of the six core ideas:

1. Series and DataFrames
2. Reading CSV files
3. Exploring datasets
4. Selecting rows and columns
5. Filtering data
6. Basic statistics - `describe()`, `info()`, `head()`

Run every cell top to bottom (`Shift + Enter`). Cell 2 writes a small CSV next to this
notebook so everything works offline - no downloads needed.

In [2]:
# The standard imports. "pd" and "np" are the universal nicknames.
import pandas as pd
import numpy as np

print("pandas version:", pd.__version__)

pandas version: 2.2.3

---
## 1. Series and DataFrames

Pandas has exactly two objects you need to know:

* **Series** = one column of data + an **index** (the labels down the side). Think of it as a
  NumPy array that remembers what each row is called.
* **DataFrame** = a whole table = several Series glued together, sharing one index.

The index is the big idea: pandas keeps labels attached to your data, so rows never get
silently mixed up.

In [3]:
# A Series from a list - pandas creates a default index 0, 1, 2, ...
s = pd.Series([10, 20, 30, 40])
print(s)
print("\nvalues:", s.values)   # the underlying NumPy array
print("index :", list(s.index))

0    10
1    20
2    30
3    40
dtype: int64

values: [10 20 30 40]
index : [0, 1, 2, 3]

In [4]:
# A Series with your own labels - now you can look values up by name.
marks = pd.Series([88, 92, 79], index=['Ali', 'Sara', 'Zara'], name='marks')
print(marks)
print("\nSara's mark:", marks['Sara'])

# Maths works element-wise, exactly like NumPy.
print("\nafter +5 bonus:\n", marks + 5)

Ali     88
Sara    92
Zara    79
Name: marks, dtype: int64

Sara's mark: 92

after +5 bonus:
 Ali     93
Sara    97
Zara    84
Name: marks, dtype: int64

In [5]:
# A DataFrame from a dictionary: each key becomes a column name, each value a column.
df = pd.DataFrame({
    'name':   ['Ali', 'Sara', 'Zara', 'Omar'],
    'age':    [21, 22, 20, 23],
    'city':   ['Lahore', 'Karachi', 'Lahore', 'Islamabad'],
    'score':  [88, 92, 79, 85]
})
df      # last line of a cell displays nicely as a table

   name  age       city  score
0   Ali   21     Lahore     88
1  Sara   22    Karachi     92
2  Zara   20     Lahore     79
3  Omar   23  Islamabad     85

In [6]:
# One column of a DataFrame IS a Series - this is why Series matter.
print(type(df['score']))
print(df['score'])

# Two or more columns (note the double brackets) give you a smaller DataFrame.
print(type(df[['name', 'score']]))

<class 'pandas.core.series.Series'>
0    88
1    92
2    79
3    85
Name: score, dtype: int64
<class 'pandas.core.frame.DataFrame'>

---
## 2. Reading CSV files

Real data usually arrives as a **CSV** (comma-separated values) - a plain text file where
each line is a row and commas separate the columns.

`pd.read_csv()` turns that file into a DataFrame in one line. First we create a sample file
so this notebook runs anywhere.

In [7]:
# Create a small sample dataset and save it as a CSV file (this is our stand-in for real data).
np.random.seed(0)

students = pd.DataFrame({
    'student_id': range(1, 16),
    'name': ['Ali','Sara','Zara','Omar','Hina','Bilal','Ayesha','Usman','Fatima','Hamza',
             'Noor','Saad','Iqra','Danish','Mariam'],
    'age': [21,22,20,23,21,24,22,20,23,21,22,25,20,23,21],
    'city': ['Lahore','Karachi','Lahore','Islamabad','Karachi','Lahore','Islamabad','Karachi',
             'Lahore','Islamabad','Karachi','Lahore','Islamabad','Karachi','Lahore'],
    'course': ['ML','ML','Data','Web','ML','Data','Web','ML','Data','Web','ML','Data','ML','Web','Data'],
    'score': [88,92,79,85,95,61,73,90,58,84,77,69,99,45,81],
    'attendance': [95,88,76,91,99,60,72,94,55,89,80,70,98,40,85]
})

students.to_csv('students.csv', index=False)   # index=False -> do not save the 0,1,2 column
print("students.csv written")

students.csv written

In [8]:
# The one line that matters: read the file back into a DataFrame.
df = pd.read_csv('students.csv')
df.head()      # head() shows the first 5 rows - always check the file loaded correctly

   student_id  name  age       city course  score  attendance
0           1   Ali   21     Lahore     ML     88          95
1           2  Sara   22    Karachi     ML     92          88
2           3  Zara   20     Lahore   Data     79          76
3           4  Omar   23  Islamabad    Web     85          91
4           5  Hina   21    Karachi     ML     95          99

In [9]:
# Useful read_csv options you will meet sooner or later (shown, not all needed here):
#   sep=';'                 -> a different separator
#   index_col='student_id'  -> use an existing column as the index
#   usecols=['name','score']-> load only some columns (saves memory on big files)
#   nrows=100               -> peek at the first 100 rows of a huge file
#   na_values=['?', 'NA']   -> treat these strings as missing values

peek = pd.read_csv('students.csv', usecols=['name', 'score'], nrows=3)
peek

   name  score
0   Ali     88
1  Sara     92
2  Zara     79

---
## 3. Exploring datasets

Before any analysis, answer three questions: **How big is it? What is in it? Does anything
look wrong?** These methods do exactly that.

In [10]:
print("shape (rows, columns):", df.shape)
print("number of rows       :", len(df))
print("column names         :", list(df.columns))

shape (rows, columns): (15, 7)
number of rows       : 15
column names         : ['student_id', 'name', 'age', 'city', 'course', 'score', 'attendance']

In [11]:
df.head(3)     # first 3 rows - the default is 5

   student_id  name  age     city course  score  attendance
0           1   Ali   21   Lahore     ML     88          95
1           2  Sara   22  Karachi     ML     92          88
2           3  Zara   20   Lahore   Data     79          76

In [12]:
df.tail(3)     # last 3 rows - good for spotting junk at the end of a file

    student_id    name  age       city course  score  attendance
12          13    Iqra   20  Islamabad     ML     99          98
13          14  Danish   23    Karachi    Web     45          40
14          15  Mariam   21     Lahore   Data     81          85

In [13]:
# sample() draws random rows - a fairer look than head(), which can be sorted.
df.sample(3, random_state=1)

   student_id    name  age       city course  score  attendance
3           4    Omar   23  Islamabad    Web     85          91
7           8   Usman   20    Karachi     ML     90          94
6           7  Ayesha   22  Islamabad    Web     73          72

In [14]:
# info() = the health check: row count, column names, non-null counts, dtypes, memory.
# If a column's non-null count is lower than the row count, you have missing values there.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  15 non-null     int64
 1   name        15 non-null     object
 2   age         15 non-null     int64
 3   city        15 non-null     object
 4   course      15 non-null     object
 5   score       15 non-null     int64
 6   attendance  15 non-null     int64
dtypes: int64(4), object(3)
memory usage: 972.0+ bytes

In [15]:
# dtypes on their own. object = text/mixed, int64/float64 = numbers.
print(df.dtypes)

# Counting missing values per column - the fastest way to spot gaps.
print("\nmissing values per column:")
print(df.isnull().sum())

student_id     int64
name          object
age            int64
city          object
course        object
score          int64
attendance     int64
dtype: object

missing values per column:
student_id    0
name          0
age           0
city          0
course        0
score         0
attendance    0
dtype: int64

In [16]:
# For a text column, ask what the categories are and how often each appears.
print("unique cities:", df['city'].unique())
print("how many unique:", df['city'].nunique())
print("\ncounts per course:")
print(df['course'].value_counts())

unique cities: ['Lahore' 'Karachi' 'Islamabad']
how many unique: 3

counts per course:
course
ML      6
Data    5
Web     4
Name: count, dtype: int64

---
## 4. Selecting rows and columns

Three tools, and it is worth being clear about which is which:

* `df['col']` - grab a **column** by name.
* `df.loc[rows, cols]` - select by **label** (the row's index label / the column's name).
  The end of a `loc` slice **is included**.
* `df.iloc[rows, cols]` - select by **integer position**, like NumPy. The end **is excluded**.

In [17]:
# --- Columns ---
print(df['name'].head(3))                # one column -> Series
df[['name', 'score', 'city']].head(3)    # several columns -> DataFrame (double brackets)

0     Ali
1    Sara
2    Zara
Name: name, dtype: object

   name  score     city
0   Ali     88   Lahore
1  Sara     92  Karachi
2  Zara     79   Lahore

In [18]:
# --- Rows by position: iloc ---
print(df.iloc[0])        # the very first row, shown as a Series
print()
df.iloc[0:3]             # rows 0,1,2 - the end is EXCLUDED, just like Python slicing

student_id         1
name             Ali
age               21
city          Lahore
course            ML
score             88
attendance        95
Name: 0, dtype: object

   student_id  name  age     city course  score  attendance
0           1   Ali   21   Lahore     ML     88          95
1           2  Sara   22  Karachi     ML     92          88
2           3  Zara   20   Lahore   Data     79          76

In [19]:
# iloc[rows, columns] - both by position
print(df.iloc[0, 1])         # row 0, column 1
print(df.iloc[0:3, 1:4])     # first 3 rows, columns 1-3
print(df.iloc[-1])           # last row

Ali
   name  age     city
0   Ali   21   Lahore
1  Sara   22  Karachi
2  Zara   20   Lahore
student_id        15
name          Mariam
age               21
city          Lahore
course          Data
score             81
attendance        85
Name: 14, dtype: object

In [20]:
# --- Rows by label: loc ---
# Our index is still 0,1,2..., so labels look like positions here - but note 0:3 gives 4 rows.
print(df.loc[0:3, ['name', 'score']])

# Set a meaningful index and the difference becomes obvious.
df_named = df.set_index('name')
print(df_named.loc['Sara'])                       # look a student up by name
print(df_named.loc[['Sara', 'Ali'], ['score', 'city']])

   name  score
0   Ali     88
1  Sara     92
2  Zara     79
3  Omar     85
student_id          2
age                22
city          Karachi
course             ML
score              92
attendance         88
Name: Sara, dtype: object
      score     city
name
Sara     92  Karachi
Ali      88   Lahore

In [21]:
# Handy shortcuts
print(df['score'].head())      # column as a Series
print(df.at[2, 'name'])        # a single cell, by label - fastest option
print(df.iat[2, 1])            # a single cell, by position

0    88
1    92
2    79
3    85
4    95
Name: score, dtype: int64
Zara
Zara

---
## 5. Filtering data

Filtering = keeping only the rows where a condition is `True`.

Write the condition first (it produces a column of True/False), then put it inside `df[...]`.
Combine conditions with `&` (and) and `|` (or) - each condition needs **its own brackets**,
because `&` binds more tightly than `>` in Python.

In [22]:
# Step 1: the condition on its own is just a True/False Series.
print((df['score'] > 85).head())

# Step 2: use it to keep matching rows.
df[df['score'] > 85]

0     True
1     True
2    False
3    False
4     True
Name: score, dtype: bool

    student_id   name  age       city course  score  attendance
0            1    Ali   21     Lahore     ML     88          95
1            2   Sara   22    Karachi     ML     92          88
4            5   Hina   21    Karachi     ML     95          99
7            8  Usman   20    Karachi     ML     90          94
12          13   Iqra   20  Islamabad     ML     99          98

In [23]:
# Combining conditions - brackets around each one are required.
high_and_present = df[(df['score'] > 80) & (df['attendance'] > 85)]
print("scored >80 AND attended >85%:")
print(high_and_present[['name', 'score', 'attendance']])

# | means OR
weak = df[(df['score'] < 60) | (df['attendance'] < 60)]
print("\nat-risk students:")
print(weak[['name', 'score', 'attendance']])

scored >80 AND attended >85%:
     name  score  attendance
0     Ali     88          95
1    Sara     92          88
3    Omar     85          91
4    Hina     95          99
7   Usman     90          94
9   Hamza     84          89
12   Iqra     99          98

at-risk students:
      name  score  attendance
8   Fatima     58          55
13  Danish     45          40

In [24]:
# isin() - match against a list of values (much cleaner than chaining several ORs).
df[df['city'].isin(['Lahore', 'Karachi'])].head()

   student_id   name  age     city course  score  attendance
0           1    Ali   21   Lahore     ML     88          95
1           2   Sara   22  Karachi     ML     92          88
2           3   Zara   20   Lahore   Data     79          76
4           5   Hina   21  Karachi     ML     95          99
5           6  Bilal   24   Lahore   Data     61          60

In [25]:
# between() for ranges (both ends included), and ~ to invert any condition.
print(df[df['age'].between(21, 22)][['name', 'age']])
print("\nNOT from Lahore:")
print(df[~(df['city'] == 'Lahore')][['name', 'city']].head())

      name  age
0      Ali   21
1     Sara   22
4     Hina   21
6   Ayesha   22
9    Hamza   21
10    Noor   22
14  Mariam   21

NOT from Lahore:
     name       city
1    Sara    Karachi
3    Omar  Islamabad
4    Hina    Karachi
6  Ayesha  Islamabad
7   Usman    Karachi

In [26]:
# Filtering text with .str - use .str.contains / .startswith / .lower first.
print(df[df['name'].str.startswith('S')][['name', 'course']])

# query() is an alternative style some people find more readable.
print(df.query('score > 90 and city == "Karachi"'))

    name course
1   Sara     ML
11  Saad   Data
   student_id  name  age     city course  score  attendance
1           2  Sara   22  Karachi     ML     92          88
4           5  Hina   21  Karachi     ML     95          99

In [27]:
# Filter, then sort, then take the top few - a very common combination.
top3 = df[df['course'] == 'ML'].sort_values('score', ascending=False).head(3)
top3[['name', 'course', 'score']]

    name course  score
12  Iqra     ML     99
4   Hina     ML     95
1   Sara     ML     92

---
## 6. Basic statistics

`describe()`, `info()` and `head()` are the three you will type most often:

* `head()` - *what does the data look like?*
* `info()` - *what types are there, and is anything missing?*
* `describe()` - *what are the numbers actually doing?*

In [28]:
# describe() summarises every numeric column at once:
#   count = non-missing values     mean/std = average and spread
#   min/max = range                25%/50%/75% = quartiles (50% is the median)
df.describe()

       student_id        age      score  attendance
count   15.000000  15.000000  15.000000   15.000000
mean     8.000000  21.866667  78.400000   79.466667
std      4.472136   1.505545  14.994285   17.315834
min      1.000000  20.000000  45.000000   40.000000
25%      4.500000  21.000000  71.000000   71.000000
50%      8.000000  22.000000  81.000000   85.000000
75%     11.500000  23.000000  89.000000   92.500000
max     15.000000  25.000000  99.000000   99.000000

In [29]:
# include='object' summarises the TEXT columns instead:
#   unique = number of distinct values, top = most common, freq = how often it appears
df.describe(include='object')

       name    city course
count    15      15     15
unique   15       3      3
top     Ali  Lahore     ML
freq      1       6      6

In [30]:
# Individual statistics on one column, when you need just one number.
print("mean score  :", df['score'].mean())
print("median score:", df['score'].median())
print("std dev     :", df['score'].std())
print("min / max   :", df['score'].min(), "/", df['score'].max())
print("total       :", df['score'].sum())
print("count       :", df['score'].count())

mean score  : 78.4
median score: 81.0
std dev     : 14.994284625435501
min / max   : 45 / 99
total       : 1176
count       : 15

In [31]:
# Run a statistic across every numeric column at once.
print(df[['age', 'score', 'attendance']].mean())

# Correlation: how strongly do two columns move together? (+1 together, -1 opposite, 0 unrelated)
print("\ncorrelation:")
print(df[['age', 'score', 'attendance']].corr())

age           21.866667
score         78.400000
attendance    79.466667
dtype: float64

correlation:
                 age     score  attendance
age         1.000000 -0.665097   -0.627620
score      -0.665097  1.000000    0.981089
attendance -0.627620  0.981089    1.000000

In [32]:
# groupby = split the data into groups, apply a statistic, combine the results.
print("average score per course:")
print(df.groupby('course')['score'].mean())

print("\nseveral statistics at once:")
print(df.groupby('city')['score'].agg(['count', 'mean', 'max']))

average score per course:
course
Data    69.600000
ML      90.166667
Web     71.750000
Name: score, dtype: float64

several statistics at once:
           count       mean  max
city
Islamabad      4  85.250000   99
Karachi        5  79.800000   95
Lahore         6  72.666667   88

In [33]:
# Putting it all together: the routine to run on any new dataset.
print("1. SHAPE   ->", df.shape)
print("\n2. HEAD"); print(df.head(3))
print("\n3. INFO");  df.info()
print("\n4. MISSING"); print(df.isnull().sum())
print("\n5. DESCRIBE"); print(df.describe())

1. SHAPE   -> (15, 7)

2. HEAD
   student_id  name  age     city course  score  attendance
0           1   Ali   21   Lahore     ML     88          95
1           2  Sara   22  Karachi     ML     92          88
2           3  Zara   20   Lahore   Data     79          76

3. INFO
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   student_id  15 non-null     int64
 1   name        15 non-null     object
 2   age         15 non-null     int64
 3   city        15 non-null     object
 4   course      15 non-null     object
 5   score       15 non-null     int64
 6   attendance  15 non-null     int64
dtypes: int64(4), object(3)
memory usage: 972.0+ bytes

4. MISSING
student_id    0
name          0
age           0
city          0
course        0
score         0
attendance    0
dtype: int64

5. DESCRIBE
       student_id        age      score  attendance
count   15.000000  15.000000  15.000000   15.000000
mean     8.000000  21.866667  78.400000   79.466667
std      4.472136   1.505545  14.994285   17.315834
min      1.000000  20.000000  45.000000   40.000000
25%      4.500000  21.000000  71.000000   71.000000
50%      8.000000  22.000000  81.000000   85.000000
75%     11.500000  23.000000  89.000000   92.500000
max     15.000000  25.000000  99.000000   99.000000

---
## Quick recap

| Task | Code |
|---|---|
| Build data | `pd.Series([...])`, `pd.DataFrame({...})` |
| Load a file | `pd.read_csv('file.csv')` |
| First look | `.head()`, `.tail()`, `.shape`, `.columns` |
| Health check | `.info()`, `.isnull().sum()`, `.dtypes` |
| Pick columns | `df['col']`, `df[['a','b']]` |
| Pick rows | `df.loc[label]` (by name), `df.iloc[0:3]` (by position) |
| Filter | `df[df['score'] > 80]`, `&`, `|`, `.isin()`, `.between()` |
| Summarise | `.describe()`, `.mean()`, `.value_counts()`, `.groupby()` |

Together with the NumPy notebook, this is the toolkit every ML project starts with.